// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_msg_2eproto__INCLUDED
#define PROTOBUF_msg_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_msg_2eproto();
void protobuf_AssignDesc_msg_2eproto();
void protobuf_ShutdownFile_msg_2eproto();

class Pixel;
class Packet;

// ===================================================================

class Pixel : public ::google::protobuf::Message {
 public:
  Pixel();
  virtual ~Pixel();

  Pixel(const Pixel& from);

  inline Pixel& operator=(const Pixel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Pixel& default_instance();

  void Swap(Pixel* other);

  // implements Message ----------------------------------------------

  Pixel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Pixel& from);
  void MergeFrom(const Pixel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 r = 1;
  inline bool has_r() const;
  inline void clear_r();
  static const int kRFieldNumber = 1;
  inline ::google::protobuf::int32 r() const;
  inline void set_r(::google::protobuf::int32 value);

  // required int32 g = 2;
  inline bool has_g() const;
  inline void clear_g();
  static const int kGFieldNumber = 2;
  inline ::google::protobuf::int32 g() const;
  inline void set_g(::google::protobuf::int32 value);

  // required int32 b = 3;
  inline bool has_b() const;
  inline void clear_b();
  static const int kBFieldNumber = 3;
  inline ::google::protobuf::int32 b() const;
  inline void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Pixel)
 private:
  inline void set_has_r();
  inline void clear_has_r();
  inline void set_has_g();
  inline void clear_has_g();
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 r_;
  ::google::protobuf::int32 g_;
  ::google::protobuf::int32 b_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static Pixel* default_instance_;
};
// -------------------------------------------------------------------

class Packet : public ::google::protobuf::Message {
 public:
  Packet();
  virtual ~Packet();

  Packet(const Packet& from);

  inline Packet& operator=(const Packet& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Packet& default_instance();

  void Swap(Packet* other);

  // implements Message ----------------------------------------------

  Packet* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Packet& from);
  void MergeFrom(const Packet& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional int32 tX = 2;
  inline bool has_tx() const;
  inline void clear_tx();
  static const int kTXFieldNumber = 2;
  inline ::google::protobuf::int32 tx() const;
  inline void set_tx(::google::protobuf::int32 value);

  // optional int32 tY = 3;
  inline bool has_ty() const;
  inline void clear_ty();
  static const int kTYFieldNumber = 3;
  inline ::google::protobuf::int32 ty() const;
  inline void set_ty(::google::protobuf::int32 value);

  // optional int32 tileSize = 4;
  inline bool has_tilesize() const;
  inline void clear_tilesize();
  static const int kTileSizeFieldNumber = 4;
  inline ::google::protobuf::int32 tilesize() const;
  inline void set_tilesize(::google::protobuf::int32 value);

  // repeated .Pixel pixel = 5;
  inline int pixel_size() const;
  inline void clear_pixel();
  static const int kPixelFieldNumber = 5;
  inline const ::Pixel& pixel(int index) const;
  inline ::Pixel* mutable_pixel(int index);
  inline ::Pixel* add_pixel();
  inline const ::google::protobuf::RepeatedPtrField< ::Pixel >&
      pixel() const;
  inline ::google::protobuf::RepeatedPtrField< ::Pixel >*
      mutable_pixel();

  // @@protoc_insertion_point(class_scope:Packet)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_tx();
  inline void clear_has_tx();
  inline void set_has_ty();
  inline void clear_has_ty();
  inline void set_has_tilesize();
  inline void clear_has_tilesize();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::int32 tx_;
  ::google::protobuf::int32 ty_;
  ::google::protobuf::int32 tilesize_;
  ::google::protobuf::RepeatedPtrField< ::Pixel > pixel_;
  friend void  protobuf_AddDesc_msg_2eproto();
  friend void protobuf_AssignDesc_msg_2eproto();
  friend void protobuf_ShutdownFile_msg_2eproto();

  void InitAsDefaultInstance();
  static Packet* default_instance_;
};
// ===================================================================


// ===================================================================

// Pixel

// required int32 r = 1;
inline bool Pixel::has_r() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Pixel::set_has_r() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Pixel::clear_has_r() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Pixel::clear_r() {
  r_ = 0;
  clear_has_r();
}
inline ::google::protobuf::int32 Pixel::r() const {
  // @@protoc_insertion_point(field_get:Pixel.r)
  return r_;
}
inline void Pixel::set_r(::google::protobuf::int32 value) {
  set_has_r();
  r_ = value;
  // @@protoc_insertion_point(field_set:Pixel.r)
}

// required int32 g = 2;
inline bool Pixel::has_g() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Pixel::set_has_g() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Pixel::clear_has_g() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Pixel::clear_g() {
  g_ = 0;
  clear_has_g();
}
inline ::google::protobuf::int32 Pixel::g() const {
  // @@protoc_insertion_point(field_get:Pixel.g)
  return g_;
}
inline void Pixel::set_g(::google::protobuf::int32 value) {
  set_has_g();
  g_ = value;
  // @@protoc_insertion_point(field_set:Pixel.g)
}

// required int32 b = 3;
inline bool Pixel::has_b() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Pixel::set_has_b() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Pixel::clear_has_b() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Pixel::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 Pixel::b() const {
  // @@protoc_insertion_point(field_get:Pixel.b)
  return b_;
}
inline void Pixel::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:Pixel.b)
}

// -------------------------------------------------------------------

// Packet

// required uint32 type = 1;
inline bool Packet::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Packet::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Packet::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Packet::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 Packet::type() const {
  // @@protoc_insertion_point(field_get:Packet.type)
  return type_;
}
inline void Packet::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:Packet.type)
}

// optional int32 tX = 2;
inline bool Packet::has_tx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Packet::set_has_tx() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Packet::clear_has_tx() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Packet::clear_tx() {
  tx_ = 0;
  clear_has_tx();
}
inline ::google::protobuf::int32 Packet::tx() const {
  // @@protoc_insertion_point(field_get:Packet.tX)
  return tx_;
}
inline void Packet::set_tx(::google::protobuf::int32 value) {
  set_has_tx();
  tx_ = value;
  // @@protoc_insertion_point(field_set:Packet.tX)
}

// optional int32 tY = 3;
inline bool Packet::has_ty() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Packet::set_has_ty() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Packet::clear_has_ty() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Packet::clear_ty() {
  ty_ = 0;
  clear_has_ty();
}
inline ::google::protobuf::int32 Packet::ty() const {
  // @@protoc_insertion_point(field_get:Packet.tY)
  return ty_;
}
inline void Packet::set_ty(::google::protobuf::int32 value) {
  set_has_ty();
  ty_ = value;
  // @@protoc_insertion_point(field_set:Packet.tY)
}

// optional int32 tileSize = 4;
inline bool Packet::has_tilesize() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Packet::set_has_tilesize() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Packet::clear_has_tilesize() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Packet::clear_tilesize() {
  tilesize_ = 0;
  clear_has_tilesize();
}
inline ::google::protobuf::int32 Packet::tilesize() const {
  // @@protoc_insertion_point(field_get:Packet.tileSize)
  return tilesize_;
}
inline void Packet::set_tilesize(::google::protobuf::int32 value) {
  set_has_tilesize();
  tilesize_ = value;
  // @@protoc_insertion_point(field_set:Packet.tileSize)
}

// repeated .Pixel pixel = 5;
inline int Packet::pixel_size() const {
  return pixel_.size();
}
inline void Packet::clear_pixel() {
  pixel_.Clear();
}
inline const ::Pixel& Packet::pixel(int index) const {
  // @@protoc_insertion_point(field_get:Packet.pixel)
  return pixel_.Get(index);
}
inline ::Pixel* Packet::mutable_pixel(int index) {
  // @@protoc_insertion_point(field_mutable:Packet.pixel)
  return pixel_.Mutable(index);
}
inline ::Pixel* Packet::add_pixel() {
  // @@protoc_insertion_point(field_add:Packet.pixel)
  return pixel_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Pixel >&
Packet::pixel() const {
  // @@protoc_insertion_point(field_list:Packet.pixel)
  return pixel_;
}
inline ::google::protobuf::RepeatedPtrField< ::Pixel >*
Packet::mutable_pixel() {
  // @@protoc_insertion_point(field_mutable_list:Packet.pixel)
  return &pixel_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_msg_2eproto__INCLUDED
